/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/75mCOO8LUfh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export function LaunchCard({
  image,
  title,
  description,
  startNewContainer,
  imgName,
}: {
  image: string;
  title: string;
  description: string;
  startNewContainer: any;
  imgName: string;
}) {
  return (
    <Card className="w-[350px]">
      <Image
        src={image}
        width={350}
        height={150}
        alt="Project"
        className="rounded-t-lg object-cover border-b"
      />
      <div className="p-4 ">
        <h2 className="text-lg font-bold">{title}</h2>
        <p className="text-muted-foreground">{description}</p>
        <Button
          className="mt-8 w-full font-bold"
          variant={"default"}
          onClick={() => startNewContainer({ imgName })}
        >
          Launch Now
        </Button>
      </div>
    </Card>
  );
}
